In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report , confusion_matrix
import joblib

In [3]:
from sklearn.datasets import load_iris

In [4]:
data = load_iris()

In [5]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
df = pd.DataFrame(data.data, columns=data.feature_names)

In [7]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [8]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
df["target"] = data.target

In [10]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [11]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [12]:
df["target_names"] = df["target"].map({0:"setosa", 1:"versicolor", 2:"virginica"})

In [13]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

In [14]:
df.isnull().sum()


sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
target_names         0
dtype: int64

In [15]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

In [16]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

In [21]:
binary_df =df[df["target"]!=2]

In [22]:
binary_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target target_names  
0        0       setosa  
1        0       setosa  
2        0       setosa  
3        0       setosa  
4        0       setosa  
..     ...          ...  
95       1   versicolor  
96       1   versicolor  
97       1   versicolor  
98       1   versicolor  
99       1   versicolor  

[100 rows x 6 columns]

In [24]:
x_binary = binary_df[['sepal length (cm)',"sepal width (cm)", "petal length (cm)", "petal width (cm)"]]

In [25]:
x_binary

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [26]:
y_binary = binary_df[["target"]]

In [27]:
y_binary

target
0        0
1        0
2        0
3        0
4        0
..     ...
95       1
96       1
97       1
98       1
99       1

[100 rows x 1 columns]

In [28]:
x_train , x_test , y_train,y_test = train_test_split(x_binary,y_binary , test_size= .2)

In [33]:
x_train

array([[-0.53813351,  1.37949789, -0.8695185 , -0.80093098],
       [-0.07355782, -0.29262076,  1.1925807 ,  1.31141446],
       [ 1.78474495, -0.29262076,  1.12384406,  1.13538567],
       [-0.84785064, -0.29262076, -0.93825514, -0.97695977],
       [-1.62214346, -0.29262076, -1.00699178, -0.97695977],
       [-1.0027092 , -0.08360593, -0.80078186, -0.97695977],
       [ 1.93960351, -0.29262076,  1.5362639 ,  1.66347203],
       [-0.53813351,  0.75245339, -0.93825514, -0.97695977],
       [-0.84785064, -0.08360593, -0.8695185 , -1.15298855],
       [-1.31242633,  0.96146822, -1.21320169, -0.97695977],
       [ 0.08130075,  2.21555721, -0.93825514, -0.97695977],
       [-0.84785064,  0.96146822, -0.93825514, -1.15298855],
       [-1.0027092 , -0.29262076, -0.93825514, -0.80093098],
       [-0.53813351,  1.37949789, -0.59457194, -0.62490219],
       [ 1.16531069, -0.50163559,  1.05510742,  0.95935689],
       [-0.69299207,  0.75245339, -1.00699178, -0.80093098],
       [-0.22841638,  1.

In [29]:
x_train.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count          80.000000         80.000000          80.000000   
mean            5.447500          3.140000           2.765000   
std             0.649825          0.481453           1.464007   
min             4.400000          2.000000           1.000000   
25%             5.000000          2.900000           1.400000   
50%             5.350000          3.100000           1.700000   
75%             5.925000          3.425000           4.300000   
max             7.000000          4.400000           5.100000   

       petal width (cm)  
count         80.000000  
mean           0.755000  
std            0.571673  
min            0.100000  
25%            0.200000  
50%            0.400000  
75%            1.300000  
max            1.800000

In [30]:
scaler = StandardScaler()
x_train  = scaler.fit_transform(x_train)

In [31]:
x_test = scaler.transform(x_test)

In [32]:
x_train

array([[-0.53813351,  1.37949789, -0.8695185 , -0.80093098],
       [-0.07355782, -0.29262076,  1.1925807 ,  1.31141446],
       [ 1.78474495, -0.29262076,  1.12384406,  1.13538567],
       [-0.84785064, -0.29262076, -0.93825514, -0.97695977],
       [-1.62214346, -0.29262076, -1.00699178, -0.97695977],
       [-1.0027092 , -0.08360593, -0.80078186, -0.97695977],
       [ 1.93960351, -0.29262076,  1.5362639 ,  1.66347203],
       [-0.53813351,  0.75245339, -0.93825514, -0.97695977],
       [-0.84785064, -0.08360593, -0.8695185 , -1.15298855],
       [-1.31242633,  0.96146822, -1.21320169, -0.97695977],
       [ 0.08130075,  2.21555721, -0.93825514, -0.97695977],
       [-0.84785064,  0.96146822, -0.93825514, -1.15298855],
       [-1.0027092 , -0.29262076, -0.93825514, -0.80093098],
       [-0.53813351,  1.37949789, -0.59457194, -0.62490219],
       [ 1.16531069, -0.50163559,  1.05510742,  0.95935689],
       [-0.69299207,  0.75245339, -1.00699178, -0.80093098],
       [-0.22841638,  1.

In [34]:
svm_binary = SVC(kernel='rbf',C=60.0,probability=True)

In [35]:
svm_binary.fit(x_train, y_train)

c:\Users\shiva\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=60.0, probability=True)

In [36]:
svm_binary.predict(x_test)

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0])

In [37]:
print("binary class classification report:\n",classification_report(y_test ,svm_binary.predict(x_test) ))

binary class classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00        13

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [38]:
joblib.dump(svm_binary ,'svm_binary.pkl')

['svm_binary.pkl']

MULTI CLASS CLASSIFICATION

In [47]:
x_multi = df[['sepal length (cm)',	'sepal width (cm)',	'petal length (cm)',	'petal width (cm)'	]]

In [48]:
x_multi

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [44]:
y_multi = df["target"]

In [45]:
y_multi

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [49]:
x_train_multi , x_test_multi , y_train_multi , y_test_multi = train_test_split(x_multi,y_multi,test_size=.2)

In [50]:
svm_multi = SVC(kernel="linear")

In [51]:
svm_multi.fit(x_train_multi,y_train_multi)

SVC(kernel='linear')

In [52]:
svm_multi.predict(x_test_multi)

array([0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 1, 0, 2, 2, 2, 2, 2, 0, 1, 1, 1, 0,
       2, 0, 0, 0, 2, 1, 2, 1])

LOGISTIC REGRESSION

In [53]:
from sklearn.linear_model import LogisticRegression

In [54]:
x_train, x_test, y_train, y_test

(array([[-0.53813351,  1.37949789, -0.8695185 , -0.80093098],
        [-0.07355782, -0.29262076,  1.1925807 ,  1.31141446],
        [ 1.78474495, -0.29262076,  1.12384406,  1.13538567],
        [-0.84785064, -0.29262076, -0.93825514, -0.97695977],
        [-1.62214346, -0.29262076, -1.00699178, -0.97695977],
        [-1.0027092 , -0.08360593, -0.80078186, -0.97695977],
        [ 1.93960351, -0.29262076,  1.5362639 ,  1.66347203],
        [-0.53813351,  0.75245339, -0.93825514, -0.97695977],
        [-0.84785064, -0.08360593, -0.8695185 , -1.15298855],
        [-1.31242633,  0.96146822, -1.21320169, -0.97695977],
        [ 0.08130075,  2.21555721, -0.93825514, -0.97695977],
        [-0.84785064,  0.96146822, -0.93825514, -1.15298855],
        [-1.0027092 , -0.29262076, -0.93825514, -0.80093098],
        [-0.53813351,  1.37949789, -0.59457194, -0.62490219],
        [ 1.16531069, -0.50163559,  1.05510742,  0.95935689],
        [-0.69299207,  0.75245339, -1.00699178, -0.80093098],
        

In [57]:
logistic_regression_binary = LogisticRegression()
logistic_regression_binary.fit(x_train, y_train)

c:\Users\shiva\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [58]:
logistic_regression_binary.predict(x_test)

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0])

In [59]:
confusion_matrix(y_test,logistic_regression_binary.predict(x_test) )

array([[ 7,  0],
       [ 0, 13]], dtype=int64)